### ISSUE TITLE
System.NullReferenceException has been thrown on Android version 

### ISSUE THREAD

**Issue by N4511** [officialdoniald/Xamarin.Forms.MockLocation#1]
Hi I get System.NullReferenceException has been thrown on app.xaml.cs on line 19 and on MainActivity.cs line 49.
<img width="1367" alt="Screenshot 2020-06-17 at 20 15 58" src="https://user-images.githubusercontent.com/67072793/84940278-85f36700-b0d7-11ea-87e4-7d4a685b50ee.png">

**Comment by N4511** [comment]
Managed to solve the issue. It was missing the access to the android.permission.ACCESS_FINE_LOCATION. 
Thanks a lot for the great article.

**Comment by officialdoniald** [comment]
Nice to hear you, thank you very much. 😄
